data:
  base_path: /data2/yuanx/QoEData/SQoE-III/videos/mp4
  quailty_num:
    # - 58
    - 61
    - 11
    - 11
    - 11
    - 63
    - 11
    - 11
    - 11
    - 11
    - 11
    - 62
    - 11
    - 11
    - 61
    - 11
    - 11
    - 11
    - 11
    - 11
  video_suffix: mp4
  video_list:
    # - BigBuckBunny
    - BirdOfPrey
    - Cheetah
    - CostaRica
    - CSGO
    - FCB
    - FrozenBanff
    - Mtv
    - PuppiesBath
    - RoastDuck
    - RushHour
    - Ski
    - SlideEditing
    - TallBuildings
    - TearsOfSteel1
    - TearsOfSteel2
    - TrafficAndBuilding
    - Transformer
    - Valentines
    - ZapHighlight
model_path: /data2/yuanx/QoEData/sailency-models/TASED-Net/models/
output_path: /data2/yuanx/QoEData/sailency-models/TASED-Net/sailency_pickles/
